name: BackEnd - Build, Push, Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'BackEnd/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./BackEnd
          file: ./BackEnd/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Set up SSH key
        run: |
          echo "${{ secrets.KEY_VALUE }}" > key.pem
          chmod 600 key.pem

      - name: Pull Docker image on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@3.129.89.133 'sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest'

      - name: Stop and remove existing container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@3.129.89.133 'sudo docker stop backend || true'
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@3.129.89.133 'sudo docker rm backend || true'

      - name: Run new container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@3.129.89.133 'sudo docker run -d --name backend -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest'
