name: FrontEnd - Build, Push, Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'FrontEnd/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./FrontEnd
          file: ./FrontEnd/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          build-args: |
            VITE_API_URL=http://18.216.2.23:3000

      - name: Set up SSH key
        run: |
          echo "${{ secrets.KEY_VALUE }}" > key.pem
          chmod 600 key.pem

      - name: Pull Docker image on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@18.216.2.23 'sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest'

      - name: Stop and remove existing container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@18.216.2.23 'sudo docker stop frontend || true'
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@18.216.2.23 'sudo docker rm frontend || true'

      - name: Run new container
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@18.216.2.23 'sudo docker run -d --name frontend -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest'
